version: "3.8"

services:

  idf-sdk:
    container_name: idf-sdk
    image: "espressif/idf:v4.4.2"
    working_dir: /project
    volumes:
      - "./:/project"
    restart: "on-failure"
    env_file:
      - .env
    command: idf.py build 
    tty: true
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0

